// This file was autogenerated from cfn.ts using @guardian/cdk-cli
// It is a starting point for migration to CDK *only*. Please check the output carefully before deploying

import path from 'path';
import { CfnInclude } from '@aws-cdk/cloudformation-include';
import type { App } from '@aws-cdk/core';
import type { GuStackProps, GuStageParameter } from '@guardian/cdk/lib/constructs/core';
import { GuStack } from '@guardian/cdk/lib/constructs/core';

const yamlTemplateFilePath = path.join(__dirname, '../cfn.yaml');

export class DotcomComponents extends GuStack {
    constructor(scope: App, id: string, props: GuStackProps) {
        super(scope, id, props);

        new CfnInclude(this, 'Template', {
            templateFile: yamlTemplateFilePath,
            parameters: {
                Stage: this.getParam<GuStageParameter>('Stage'), // TODO `GuStageParameter` could be a singleton to simplify this
            },
        });

        /* Parameters */
        // TODO: Consider if any of the parameter constructs from @guardian/cdk could be used here
        // https://github.com/guardian/cdk/blob/main/src/constructs/core/parameters.ts
    }
}
