import React from 'react';

type Props = {};

export const EpicEnvironment: React.FC<Props> = (allProps: Props) => {
    return <div>{articles.map(article => (<span>{article}</span>))}</div>;
};

const articles = [
    'https://www.theguardian.com/environment/2020/mar/18/tip-of-the-iceberg-is-our-destruction-of-nature-responsible-for-covid-19-aoe',
    'https://www.theguardian.com/world/2020/mar/25/coronavirus-nature-is-sending-us-a-message-says-un-environment-chief',
    'https://www.theguardian.com/world/2020/jul/06/coronavirus-world-treating-symptoms-not-cause-pandemics-un-report',
    'https://www.theguardian.com/world/2020/jul/23/preventing-next-pandemic-fraction-cost-covid-19-economic-fallout',
    'https://www.theguardian.com/world/2020/apr/27/halt-destruction-nature-worse-pandemics-top-scientists',
    'https://www.theguardian.com/society/2020/jun/09/world-faces-worst-food-crisis-50-years-un-coronavirus',
    'https://www.theguardian.com/global-development/2020/apr/21/coronavirus-pandemic-will-cause-famine-of-biblical-proportions',
    'https://www.theguardian.com/environment/2020/may/14/everyones-on-top-of-you-sneezing-and-coughing-life-inside-irelands-meat-plants-covid-19',
    'https://www.theguardian.com/world/2020/may/04/is-air-pollution-making-the-coronavirus-pandemic-even-more-deadly',
    'https://www.theguardian.com/world/2020/jul/13/compelling-evidence-air-pollution-worsens-coronavirus-study',
    'https://www.theguardian.com/environment/2020/apr/24/coronavirus-detected-particles-air-pollution',
    'https://www.theguardian.com/world/2020/jul/19/covid-19-impact-on-ethnic-minorities-linked-to-housing-and-air-pollution',
    'https://www.theguardian.com/environment/series/the-green-recovery',
    'https://www.theguardian.com/australia-news/series/the-green-recovery',
    'https://www.theguardian.com/environment/2020/may/19/how-renewable-energy-could-power-britains-economic-recovery',
    'https://www.theguardian.com/environment/2020/may/18/a-new-normal-how-coronavirus-will-transform-transport-in-britains-cities',
    'https://www.theguardian.com/environment/2020/may/18/coronavirus-offers-chance-to-create-fairer-uk-food-supply-chain-say-experts',
    'https://www.theguardian.com/world/2020/may/17/is-covid-19-crisis-the-catalyst-for-the-greening-of-worlds-airlines',
    'https://www.theguardian.com/environment/2020/jul/07/fossil-fuel-industry-coronavirus-aid-us-analysis',
    'https://www.theguardian.com/australia-news/2020/jun/13/gas-completely-dominated-discussion-about-covid-19-recovery-commission-adviser-says',
    'https://www.theguardian.com/environment/2020/apr/17/polluter-bailouts-and-lobbying-during-covid-19-pandemic',
    'https://www.theguardian.com/politics/2020/jul/06/britain-beyond-lockdown-what-we-learned-from-two-weeks-on-the-road',
    'https://www.theguardian.com/environment/2020/aug/07/covid-19-lockdown-will-have-negligible-impact-on-climate-crisis-study',
    'https://www.theguardian.com/environment/2020/jan/13/ocean-temperatures-hit-record-high-as-rate-of-heating-accelerates',
    'https://www.theguardian.com/world/2020/feb/13/antarctic-temperature-rises-above-20c-first-time-record',
    'https://www.theguardian.com/environment/2019/nov/18/amazon-deforestation-at-highest-level-in-a-decade',
    'https://www.theguardian.com/environment/series/the-polluters',
    'https://www.theguardian.com/environment/2019/oct/09/revealed-20-firms-third-carbon-emissions',
    'https://www.theguardian.com/environment/2019/oct/11/google-contributions-climate-change-deniers',
    'https://www.theguardian.com/environment/2019/oct/10/exclusive-carmakers-opponents-climate-action-us-europe-emissions',
    'https://www.theguardian.com/us-news/2020/jul/27/global-climate-fight-could-be-lost-trump-re-elected',
    'https://www.theguardian.com/us-news/2020/jul/28/us-racial-injustices-will-worsen-climate-crisis-escalates',
    'https://www.theguardian.com/environment/series/the-frontline',
    'https://www.theguardian.com/environment/ng-interactive/2020/feb/11/counting-the-cost-of-australias-summer-of-dread',
    'https://www.theguardian.com/environment/ng-interactive/2020/jul/29/australia-after-the-bushfires-aoe',
    'https://www.theguardian.com/environment/2020/mar/25/great-barrier-reef-suffers-third-mass-coral-bleaching-event-in-five-years',
    'https://www.theguardian.com/environment/2019/sep/23/greta-thunberg-speech-un-2019-address',
    'https://www.theguardian.com/environment/2020/aug/04/evolution-of-extinction-rebellion-climate-emergency-protest-coronavirus-pandemic',
    'https://www.theguardian.com/technology/2020/feb/21/climate-tweets-twitter-bots-analysis',
    'https://www.theguardian.com/environment/series/the-age-of-extinction',
    'https://www.theguardian.com/environment/2020/jan/07/honeybees-deaths-almonds-hives-aoe',
    'https://www.theguardian.com/environment/2019/sep/16/1m-a-minute-the-farming-subsidies-destroying-the-world',
    'https://www.theguardian.com/environment/2020/jul/01/more-than-350-elephants-dead-in-mysterious-mass-die-off-botswana-aoe',
    'https://www.theguardian.com/uk-news/2020/feb/02/fears-grow-over-hs2s-potential-impact-on-biodiversity',
    'https://www.theguardian.com/uk-news/2020/feb/02/will-hs2-really-help-cut-the-uks-carbon-footprint',
    'https://www.theguardian.com/environment/2019/nov/13/air-pollution-particles-linked-to-brain-cancer-in-new-research',
    'https://www.theguardian.com/us-news/series/cancer-town',
    'https://www.theguardian.com/environment/2019/dec/27/revealed-microplastic-pollution-is-raining-down-on-city-dwellers',
    'https://www.theguardian.com/environment/2020/jul/01/water-firms-raw-sewage-england-rivers',
    'https://www.theguardian.com/us-news/2020/jun/23/millions-of-americans-cant-afford-water-bills-rise',
    'https://www.theguardian.com/world/ng-interactive/2020/apr/09/sound-of-icebergs-melting-journey-into-antarctic-jonathan-watts-greenpeace',
    'https://www.theguardian.com/tv-and-radio/2019/oct/22/david-attenborough-climate-change-bbc',
    'https://www.theguardian.com/environment/2020/mar/27/canada-mourns-takaya-the-lone-sea-wolf-whose-spirit-captured-the-world-aoe',
    'https://www.theguardian.com/world/2019/dec/18/how-water-is-helping-to-end-the-first-climate-change-war',
    'https://www.theguardian.com/environment/2020/apr/08/scientists-create-mutant-enzyme-that-recycles-plastic-bottles-in-hours',
    'https://www.theguardian.com/environment/2020/feb/17/beavers-cut-flooding-and-pollution-and-boost-wildlife-populations',
    'https://www.theguardian.com/environment/2020/aug/06/englands-first-wild-beavers-for-400-years-allowed-to-live-on-river-otter',
    'https://www.theguardian.com/environment/2020/jul/14/farmers-wildeast-hatch-plan-return-area-size-dorset-wild-nature-east-anglia',
    'https://www.theguardian.com/environment/2020/jul/10/wild-bison-to-return-to-uk-kent',
];
