name: Chromatic
on:
    push:
jobs:
    upload-storybook:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3
              with:
                  fetch-depth: 0
                  cache: yarn
            - name: Install Node
              uses: actions/setup-node@v3

            - name: Install
              run: |
                  yarn
                  yarn setup
            - uses: chromaui/action@v11.3.0
              with:
                  workingDir: packages/modules
                  projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
                  token: ${{ secrets.GITHUB_TOKEN }}
                  buildScriptName: 'build-storybook'
                  exitOnceUploaded: true
                  onlyChanged: '!(main)' # only turbosnap on non-main branches
