name: Build dotcom-components

on:
  pull_request:
    branches:
      - "**"
  push:
    branches:
      - main

jobs:
  dotcom-components:
    if: >-
      (github.actor != 'dependabot[bot]') &&
        (github.event.pull_request.head.repo.owner.login == 'guardian' ||
          github.event_name == 'push')
    # Required by actions-assume-aws-role
    permissions:
      id-token: write
      contents: read

    name: dotcom-components
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
            node-version-file: '.nvmrc'

      - name: Test + build
        run: |
          npm install -g yarn
          yarn install
          yarn setup
          yarn lint
          yarn test

          NODE_ENV=production yarn server build
          NODE_ENV=production NODE_OPTIONS="--max-old-space-size=16384" yarn modules build

      - name: cdk
        working-directory: ./cdk
        run: |
          npm install -g yarn
          yarn install
          yarn lint
          yarn test
          yarn synth

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.GU_RIFF_RAFF_ROLE_ARN }}
          aws-region: eu-west-1

      - name: riffraff
        run: |
          export LAST_TEAMCITY_BUILD=4000
          export GITHUB_RUN_NUMBER=$(( $GITHUB_RUN_NUMBER + $LAST_TEAMCITY_BUILD ))

          npm install -g yarn
          yarn install
          yarn run riffraff
