name: Snyk

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  security:
    runs-on: ubuntu-latest
    env:
      SNYK_COMMAND: test
    steps:
      - name: Checkout branch
        if: github.ref == 'refs/heads/main'
        uses: actions/checkout@v2

      - name: Set command to monitor
        if: github.ref == 'refs/heads/main'
        run: echo "SNYK_COMMAND=monitor" >> $GITHUB_ENV

      - name: Run Snyk to check for vulnerabilities
        if: github.ref == 'refs/heads/main'
        uses: snyk/actions/node@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=guardian-growth --project-name=${{ github.repository }} --file=./pnpm-lock.yaml
          command: ${{ env.SNYK_COMMAND }}
